### ISSUE TITLE
Chat room not recieving replies.

### ISSUE THREAD

**Issue by DFyson** [Yakoo63/gtalksms#276]
After opening a chat room eg `chat:Johnny`, I can send messages from that chat room and the recipient gets them which is great. However when the recipient replies, the message ends up in the main chat, not the chat room.
Related issue #117
Using GTalkSMS 5.0.1 with Pidgin

**Comment by Yakoo63** [comment]
Hello 
Can you test by changing the setting :
Settings > Notification settings > Incoming SMS > Both

**Comment by DFyson** [comment]
Oops I totally missed that option.
