### ISSUE TITLE
Latest release 5.1.1 available anywhere?

### ISSUE THREAD

**Issue by bbinet** [Yakoo63/gtalksms#281]
I'm reinstalling my phone from scratch but cannot find GtalkSMS software anywhere anymore...

Does anyone knows where we can download latest release (5.1.1) of GtalkSMS ?

**Comment by Yakoo63** [comment]
Unfortunately, Google removed GTalkSMS because the SMS access was required for the application...

**Comment by bbinet** [comment]
@Yakoo63 Ok, thank you for the info.
Do you think you could create a new 5.1.1 release page [on github](https://github.com/Yakoo63/gtalksms/releases) and upload the apk here?

**Comment by Yakoo63** [comment]
Here is the link https://github.com/Yakoo63/gtalksms/releases/tag/5.1.0.86
It's the latest version

**Comment by bbinet** [comment]
Thank you!
