### ISSUE TITLE
https://flattr.com/thing/130193 & paypal valid ids?

### ISSUE THREAD

**Issue by ghost** [Yakoo63/gtalksms#286]
@Yakoo63 
* https://flattr.com/thing/130193 is 404, did you replaced it?
* https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=WQDV6S67WAC7A&lc=US&item_name=GTalkSMS&item_number=WEB&currency_code=EUR&bn= is still valid?

**Comment by Yakoo63** [comment]
Hey
The application is no more supported.
The flattr is closed and the paypal still ok.

**Comment by ghost** [comment]
@Yakoo63 
updated in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549
* thank you
